# Generated by Django 5.1.4 on 2025-01-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treffen', '0002_buddy_owner_location_owner_meetup_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddy',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
