# Generated by Django 5.1.4 on 2025-01-10 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treffen', '0003_alter_buddy_name_alter_location_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='buddy',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='meetup',
            unique_together={('owner', 'name', 'when')},
        ),
    ]
