# Generated by Django 5.1.4 on 2025-01-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treffen', '0004_alter_buddy_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='location_unique_name_owner', violation_error_message='Location with this name already exists.'),
        ),
    ]
