# Generated by Django 5.1.4 on 2025-01-10 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treffen', '0005_alter_location_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location',
            name='location_unique_name_owner',
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('owner', 'name')},
        ),
    ]
