# Generated by Django 5.1.4 on 2025-01-11 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treffen', '0006_remove_location_location_unique_name_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='when',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='meetup',
            unique_together={('owner', 'name', 'date')},
        ),
    ]
