# Generated by Django 5.1.4 on 2025-01-11 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treffen', '0007_rename_when_meetup_date_alter_meetup_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meetup',
            unique_together={('owner', 'name', 'date', 'location')},
        ),
    ]
