# Generated by Django 5.1.4 on 2025-01-19 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treffen', '0010_category_buddy_category_meetup_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddy',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treffen.category'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treffen.category'),
        ),
    ]
