# Generated by Django 5.1.4 on 2025-01-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treffen', '0011_alter_buddy_category_alter_meetup_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.FloatField(blank=True),
        ),
    ]
