# Generated by Django 5.1.4 on 2025-01-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treffen', '0012_alter_location_lat_alter_location_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
