# Generated by Django 5.1.4 on 2025-02-15 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treffen', '0013_alter_location_lat_alter_location_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=250)),
                ('referrer', models.CharField(max_length=250)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='meetup',
            name='date',
            field=models.DateField(default=datetime.date(2025, 2, 15)),
        ),
    ]
