# Generated by Django 5.1.4 on 2025-02-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treffen', '0014_logger_alter_meetup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='referrer',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
