# Generated by Django 5.1.4 on 2025-02-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treffen', '0015_alter_logger_referrer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logger',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='logger',
            name='referrer',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
