# Generated by Django 5.1.4 on 2025-02-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treffen', '0016_alter_logger_options_alter_logger_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='logger',
            name='method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
