# Generated by Django 5.1.6 on 2025-03-01 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treffen', '0017_logger_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.IntegerField(choices=[(1, 'Buddy'), (2, 'Meetup')], default=1),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='date',
            field=models.DateField(default=datetime.date(2025, 3, 1)),
        ),
    ]
