# Generated by Django 5.1.6 on 2025-03-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treffen', '0019_location_category_alter_category_category_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.IntegerField(choices=[(1, 'Buddy'), (2, 'Location')], default=1),
        ),
    ]
