# Generated by Django 5.1.6 on 2026-04-19 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treffen', '0020_remove_meetup_category_alter_category_category_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buddy',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='meetup',
            name='buddies_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
