# Generated by Django 5.1.6 on 2026-04-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treffen', '0021_alter_buddy_options_meetup_buddies_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
